AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  BucketName:
    Type: String
Resources:
  MyOriginAccessControl:
    Type: "AWS::CloudFront::OriginAccessControl"
    Properties:
      OriginAccessControlConfig:
        Name: !Ref BucketName
        SigningBehavior: "always" 
        OriginAccessControlOriginType: "s3"
        SigningProtocol: "sigv4" 
  MyCloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - Id: "MyOrigin"
            DomainName: !Sub "${BucketName}.s3.eu-west-1.amazonaws.com"  
            OriginAccessControlId: !Ref MyOriginAccessControl  
            S3OriginConfig:
              OriginAccessIdentity: ''
        Enabled: "true"
        DefaultCacheBehavior:
          TargetOriginId: "MyOrigin"
          ViewerProtocolPolicy: "redirect-to-https"  
          AllowedMethods:
            - "GET"
            - "HEAD"
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: "none"
        DefaultRootObject: "index.html"  

