AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyOriginAccessControl:
    Type: "AWS::CloudFront::OriginAccessControl"
    Properties:
      OriginAccessControlConfig:
        Name: "test1-ui-artifacts-poc-zero-downtime"
        SigningBehavior: "always" 
        OriginAccessControlOriginType: "s3"
        SigningProtocol: "sigv4" 
  MyCloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - Id: "MyOrigin"
            DomainName: "ui-artifacts-poc-zero-downtime-v3.s3.eu-west-1.amazonaws.com"  
            S3OriginConfig:
              OriginAccessControlId: !Ref MyOriginAccessControl  

        Enabled: "true"
        DefaultCacheBehavior:
          TargetOriginId: "MyOrigin"
          ViewerProtocolPolicy: "redirect-to-https"  
          AllowedMethods:
            - "GET"
            - "HEAD"
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: "none"
        DefaultRootObject: "index.html"  

