AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation CI CD Stack for UI, API, DB and Infrastructure
Parameters:
  APIBranch:
    Type: String
  UIBranch:
    Type: String
  UIARTIFACTBUCKETNAME:
    Type: String
  BlueOrGreen:
    Type: String
    AllowedValues:
      - "blue"
      - "green"
  DEPLOYAPI:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
  RECORDNAME:
    Type: String
  HOSTEDZONEID:
    Type: String
  DEPLOYDB:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
  DEPLOYUI:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
  CANARY:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
  STABLETAG:
    Type: String
  CANARYTAG:
    Type: String
  STABLEWEIGHT:
    Type: String
  CANARYWEIGHT:
    Type: String
  CLOUDFRONTCANARY:
    Type: String
  CLOUDFRONTSTABLE:
    Type: String

Conditions:
  CondDEPLOYAPI: !Equals [!Ref DEPLOYAPI, "yes"]
  CondDEPLOYDB: !Equals [!Ref DEPLOYDB, "yes"]
  CondDEPLOYUI: !Equals [!Ref DEPLOYUI, "yes"]
  CondRUNCANARY: !Equals [!Ref CANARY, "yes"]
 
Resources:
  DynamicCodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - 'codepipeline.amazonaws.com'
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: zero-downtime-poc-dynamic-pipeline-admin-access-v3
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - '*'
                Effect: Allow
                Resource: '*'
      RoleName: 'zero-downtime-poc-dynamic-pipeline-role-v3'

  DynamicPipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      PipelineType: V2
      RestartExecutionOnUpdate: true
      ArtifactStore:
        Location: !Ref S3Bucket
        Type: S3
      Name: !Sub depoyment-dynamic-pipeline
      RoleArn: !GetAtt DynamicCodePipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - !If
              - CondDEPLOYUI
              - Name: UISource
                ActionTypeId:
                  Category: Source
                  Owner: AWS
                  Provider: GitHub
                  Version: "1"
                Configuration:
                  Owner: hitarthi051
                  Repo: poc-ui
                  Branch: !Ref UIBranch
                OutputArtifacts:
                - Name: UISource
                RunOrder: "1"
              - !Ref "AWS::NoValue"
            - !If 
              - CondDEPLOYAPI
              - Name: APISource
                ActionTypeId:
                  Category: Source
                  Owner: ThirdParty
                  Provider: GitHub
                  Version: "1"
                Configuration:
                  Owner: hitarthi051
                  Repo: poc-api
                  Branch: !Ref APIBranch
                OutputArtifacts:
                  - Name: APISource
                RunOrder: "1"
              - !Ref "AWS::NoValue"
        - !If 
          - CondDEPLOYUI
          - Name: UI
            Actions:
              - Name: UIBUILD
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: "1"
                InputArtifacts:
                  - Name: UISource
                OutputArtifacts:
                  - Name: zero-downtime-poc-UI-SourceOutput
                Configuration:
                  ProjectName: zero-downtime-poc-ui
                  EnvironmentVariables: !Sub '[{"name":"UIARTIFACTBUCKETNAME","value":"${UIARTIFACTBUCKETNAME}","type":"PLAINTEXT"}]'
                RunOrder: "1"
          # - Name: UI-Artifact-Source
          #   ActionTypeId:
          #     Category: Source
          #     Owner: AWS
          #     Provider: S3
          #     Version: '1'
          #   Configuration:
          #     S3Bucket: !Sub '${UIBuildArtifactsStoreBucket}'
          #     PollForSourceChanges: false
          #     S3ObjectKey: zero-downtime-poc-ui.zip
          #   OutputArtifacts:
          #     - Name: zero-downtime-poc-UI-SourceOutput
          #   RunOrder: '2'
          - Name: UI-deploy
            Actions:
              - Name: Deploy
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: S3
                  Version: "1"
                InputArtifacts:
                  - Name: zero-downtime-poc-UI-SourceOutput
                Configuration:
                  BucketName: !Ref UIARTIFACTBUCKETNAME
                  Extract: true
                RunOrder: "2"
          - !Ref "AWS::NoValue"
        - !If 
          - CondDEPLOYDB
          - Name: DB
            Actions:
              - Name: DB
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: "1"
                Configuration:
                  ProjectName: zero-downtime-poc-database
                  # EnvironmentVariables: !Sub '[{"name":"stage","value":"${EnvironmentName}","type":"PLAINTEXT"}, {"name":"LAMBDA","value":"central-admin","type":"PLAINTEXT"},{"name":"PIPELINE_EXECUTION_ID","value":"#{codepipeline.PipelineExecutionId}","type":"PLAINTEXT"}]'
                RunOrder: "6"
          - !Ref "AWS::NoValue"
        - !If 
          - CondDEPLOYAPI
          - Name: APIDeploy
            Actions:
              - Name: APIDeploy
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: "1"
                InputArtifacts:
                  - Name: APISource
                Configuration:
                  ProjectName: zero-downtime-poc-api
                  EnvironmentVariables: !Sub '[{"name":"STAGE","value":"${BlueOrGreen}","type":"PLAINTEXT"}]'
                RunOrder: "6"
          - !Ref "AWS::NoValue"
        - !If 
          - CondRUNCANARY
          - Name: WEIGHT_SHIFT
            Actions:
              - Name: approval
                ActionTypeId:
                  Category: Approval
                  Owner: AWS
                  Provider: Manual
                  Version: '1'
                Configuration:
                  CustomData: "test"
                RunOrder: '1'
              - Name: WEIGHT_SHIFT
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: "1"
                InputArtifacts:
                  - Name: APISource
                Configuration:
                  ProjectName: zero-downtime-poc-infrastructure-weight-shift
                  EnvironmentVariables: !Sub '[{"name":"HOSTED_ZONE_ID","value":"${HOSTEDZONEID}","type":"PLAINTEXT"},{"name":"RECORD_NAME","value":"${RECORDNAME}","type":"PLAINTEXT"},{"name":"STABLE_WEIGHT","value":"${STABLEWEIGHT}","type":"PLAINTEXT"},{"name":"CANARY_WEIGHT","value":"${CANARYWEIGHT}","type":"PLAINTEXT"},{"name":"CLOUDFRONT_CANARY","value":"${CLOUDFRONTCANARY}","type":"PLAINTEXT"},{"name":"CLOUDFRONT_STABLE","value":"${CLOUDFRONTSTABLE}","type":"PLAINTEXT"},{"name":"STABLE_TAG","value":"${STABLETAG}", {"name":"CANARY_TAG","value":"${CANARYTAG}","type":"PLAINTEXT"},"type":"PLAINTEXT"},{"name":"PIPELINE_EXECUTION_ID","value":"#{codepipeline.PipelineExecutionId}","type":"PLAINTEXT"}]'
                RunOrder: "2"
          - !Ref "AWS::NoValue"
