AWSTemplateFormatVersion: 2010-09-09
Description: Lion Heart Infrastructure

Resources:
  TestAPIGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./apigateway.yml
      TimeoutInMinutes: 30
  s3buckets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./s3.yml
      TimeoutInMinutes: 30
  cloudfront:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BucketName: "ui-artifacts-poc-zero-downtime-v3"
      TemplateURL: ./cloudfront.yml
      TimeoutInMinutes: 30
  cloudfrontB:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BucketName: "ui-artifacts-poc-zero-downtime-v3-b"
      TemplateURL: ./cloudfront.yml
      TimeoutInMinutes: 30